package dev.pseonkyaw.diametercc.domain.model;

import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A long-lived Diameter Credit-Control session identified by a globally
 * unique Session-Id (RFC 4006 §6.1, generated by the originating peer).
 *
 * <p>The session aggregates running totals across CCR-Initial, CCR-Update,
 * and CCR-Termination. Per-CCR state lives in {@link Reservation}.
 */
@Entity
@Table(name = "cc_session")
public class CcSession {

    public enum State { OPEN, TERMINATED }

    @Id
    @Column(name = "session_id", length = 255)
    private String sessionId;

    @Column(nullable = false, length = 20)
    private String msisdn;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private State state;

    @Column(name = "granted_units_total", nullable = false)
    private long grantedUnitsTotal;

    @Column(name = "used_units_total", nullable = false)
    private long usedUnitsTotal;

    @Column(name = "last_request_number", nullable = false)
    private int lastRequestNumber;

    @Column(name = "started_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime startedAt;

    @Column(name = "ended_at")
    private OffsetDateTime endedAt;

    protected CcSession() {}

    public CcSession(String sessionId, String msisdn) {
        this.sessionId = sessionId;
        this.msisdn = msisdn;
        this.state = State.OPEN;
        this.grantedUnitsTotal = 0L;
        this.usedUnitsTotal = 0L;
        this.lastRequestNumber = -1;
    }

    public String getSessionId()    { return sessionId; }
    public String getMsisdn()       { return msisdn; }
    public State getState()         { return state; }
    public long getGrantedUnitsTotal() { return grantedUnitsTotal; }
    public long getUsedUnitsTotal()    { return usedUnitsTotal; }
    public int getLastRequestNumber()  { return lastRequestNumber; }
    public OffsetDateTime getStartedAt() { return startedAt; }
    public OffsetDateTime getEndedAt()   { return endedAt; }

    public void recordGrant(long units, int requestNumber) {
        this.grantedUnitsTotal += units;
        this.lastRequestNumber = requestNumber;
    }

    public void recordUsage(long units, int requestNumber) {
        this.usedUnitsTotal += units;
        this.lastRequestNumber = requestNumber;
    }

    public void terminate(int requestNumber) {
        this.state = State.TERMINATED;
        this.endedAt = OffsetDateTime.now();
        this.lastRequestNumber = requestNumber;
    }
}
