package dev.pseonkyaw.diametercc.gy;

/**
 * Parsed Diameter Credit-Control-Request (CCR), Command-Code 272.
 *
 * <p>RFC 4006 §3.1 mandatory AVPs are required. Optional AVPs may be null.
 *
 * @param sessionId         Session-Id (263) — uniquely identifies a CC session, generated by the originating peer
 * @param originHost        Origin-Host (264)
 * @param originRealm       Origin-Realm (296)
 * @param destinationRealm  Destination-Realm (283)
 * @param authApplicationId Auth-Application-Id (258) — must be 4 for Gy
 * @param serviceContextId  Service-Context-Id (461) — opaque service identifier
 * @param ccRequestType     CC-Request-Type (416) — INITIAL/UPDATE/TERMINATION/EVENT
 * @param ccRequestNumber   CC-Request-Number (415) — monotonic counter within the session
 * @param subscriptionId    Subscription-Id (443) — typically MSISDN; nullable
 * @param requestedUnits    Requested-Service-Unit (437) — what the client asks for; nullable on TERMINATION
 * @param usedUnits         Used-Service-Unit (446) — what was consumed since last CCR; nullable on INITIAL
 * @param terminationCause  Termination-Cause (295) — only present on TERMINATION; nullable
 */
public record CreditControlRequest(
        String sessionId,
        String originHost,
        String originRealm,
        String destinationRealm,
        long authApplicationId,
        String serviceContextId,
        CcRequestType ccRequestType,
        int ccRequestNumber,
        SubscriptionId subscriptionId,
        ServiceUnit requestedUnits,
        ServiceUnit usedUnits,
        Integer terminationCause
) {
}
